export const GET_SELECTED_MARKS_SUCCESS = "GET_SELECTED_MARKS_SUCCESS";
// to get gladzor marks
export const GET_GLADZOR_REQUEST = "GET_GLADZOR_REQUEST";
export const GET_GLADZOR_SUCCESS = "GET_GLADZOR_SUCCESS";
export const GET_GLADZOR_FAILURE = "GET_GLADZOR_FAILURE";
// to get getap marks
export const GET_GETAP_REQUEST = "GET_GETAP_REQUEST";
export const GET_GETAP_SUCCESS = "GET_GETAP_SUCCESS";
export const GET_GETAP_FAILURE = "GET_GETAP_FAILURE";
// to get vernashen marks
export const GET_VERNASHEN_REQUEST = "GET_VERNASHEN_REQUEST";
export const GET_VERNASHEN_SUCCESS = "GET_VERNASHEN_SUCCESS";
export const GET_VERNASHEN_FAILURE = "GET_VERNASHEN_FAILURE";
// to get vernashen tourist places
export const GET_VERNASHENTP_REQUEST = "GET_VERNASHENTP_REQUEST";
export const GET_VERNASHENTP_SUCCESS = "GET_VERNASHENTP_SUCCESS";
export const GET_VERNASHENTP_FAILURE = "GET_VERNASHENTP_FAILURE";
// to get vernashen sell places
export const GET_VERNASHENSP_REQUEST = "GET_VERNASHENSP_REQUEST";
export const GET_VERNASHENSP_SUCCESS = "GET_VERNASHENSP_SUCCESS";
export const GET_VERNASHENSP_FAILURE = "GET_VERNASHENSP_FAILURE";
// to get vernasehn churches
export const GET_VERNASHENCHU_REQUEST = "GET_VERNASHENCHU_REQUEST";
export const GET_VERNASHENCHU_SUCCESS = "GET_VERNASHENCHU_SUCCESS";
export const GET_VERNASHENCHU_FAILURE = "GET_VERNASHENCHU_FAILURE";